spring.application.name=Streaming_service
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=streaming_service
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
