--liquibase formatted SQL

--changeset liquibase:1
create table subscription_plans(
    id             bigint generated by default as identity primary key,
    type           varchar(20) not null,
    cost_per_month numeric     not null
);
--rollback drop table subscription_plans;

--changeset liquibase:2
create table countries_codes(
    code         varchar(3) primary key,
    name         varchar(20) not null,
    is_supported boolean     not null
);
--rollback drop table countries_codes;

--changeset liquibase:3
create table roles(
    id   bigint generated by default as identity primary key,
    role varchar(15) not null
);
--rollback drop table roles;

--changeset liquibase:4
create table profiles(
    id                    bigint generated by default as identity primary key,
    user_name             varchar(50)  not null,
    password              varchar(200) not null,
    profile_photo         varchar(300),
    role_id               bigint       not null,
    country_code          bigint       not null,
    subscription_id       bigint,
    subscription_end_date Date
);
--rollback drop table profiles;

--changeset liquibase:5
create table album_types(
    id         bigint generated by default as identity primary key,
    album_type varchar(10) not null
);
--rollback drop table album_types;

--changeset liquibase:6
create table albums
(
    id           bigint generated by default as identity primary key,
    album_name   varchar(20) not null,
    release_date Date        not null,
    album_type   bigint      not null
);
--rollback drop table albums;

--changeset liquibase:7
create table tracks(
    id         bigint generated by default as identity primary key,
    track_name varchar(20) not null,
    track      bytea       not null,
    album_id   bigint      not null
);
--rollback drop table tracks;

--changeset liquibase:8
create table playlists(
    id            bigint generated by default as identity primary key,
    playlist_name varchar(20) not null
);
--rollback drop table playlists;

--changeset liquibase:9
create table labels(
    id         bigint generated by default as identity primary key,
    label_name varchar(20) not null
);
--rollback drop table labels;

--changeset liquibase:10
create table albums_labels(
    id       bigint generated by default as identity primary key,
    label_id bigint not null,
    album_id bigint not null
);
--rollback drop table albums_labels;

--changeset liquibase:11
create table genres(
    id    bigint generated by default as identity primary key,
    genre varchar(30) not null
);
--rollback drop table genres;

--changeset liquibase:12
create table tracks_playlists(
    id          bigint generated by default as identity primary key,
    track_id    bigint not null,
    playlist_id bigint not null,
    date_added  Date   not null
);
--rollback drop table tracks_playlists;

--changeset liquibase:13
create table tracks_genres(
    track_id bigint not null,
    genre_id bigint not null,
    primary key (track_id, genre_id)
);
--rollback drop table tracks_genres;

--changeset liquibase:14
create table following_followers(
    id          bigint generated by default as identity primary key,
    following_id bigint not null,
    follower_id  bigint not null
);
--rollback drop table following_followers;

--changeset liquibase:15
create table artists_albums(
    id        bigint generated by default as identity primary key,
    artist_id bigint not null,
    album_id  bigint not null
);
--rollback drop table artists_albums;

--changeset liquibase:16
create table users_playlists(
    id          bigint generated by default as identity primary key,
    user_id     bigint not null,
    playlist_id bigint not null
);
--rollback drop table users_playlists;

--changeset liquibase:17
alter table profiles
add constraint fk_role
foreign key(role_id) references roles (id);

alter table profiles
add constraint fk_country_code
foreign key(country_code) references countries_codes(code);

alter table profiles
add constraint fk_subscription
foreign key(subscription_id) references subscription_plans (id);
--rollback alter table profiles drop constraint fk_role
--rollback alter table profiles drop constraint fk_country_code
--rollback alter table profiles drop constraint fk_subscription

--changeset liquibase:18
alter table albums
add constraint fk_album_type
foreign key(album_type) references album_types (id);
--rollback alter table profiles drop constraint fk_album_type

--changeset liquibase:19
alter table tracks
add constraint fk_album_id
foreign key(album_id) references albums (id);
--rollback alter table profiles drop constraint fk_album_id

--changeset liquibase:20
alter table albums_labels
add constraint fk_label_id
foreign key(label_id) references labels (id);

alter table albums_labels
add constraint fk_album_id
foreign key(album_id) references albums (id);
--rollback alter table profiles drop constraint fk_label_id
--rollback alter table profiles drop constraint fk_album_id

--changeset liquibase:21
alter table tracks_playlists
add constraint fk_track_in_playlist
foreign key(track_id) references tracks (id);

alter table tracks_playlists
add constraint fk_playlist_id
foreign key(playlist_id) references playlists (id);
--rollback alter table profiles drop constraint fk_track_in_playlist
--rollback alter table profiles drop constraint fk_playlist_id

--changeset liquibase:22
alter table tracks_genres
add constraint fk_track_genre
foreign key(track_id) references tracks (id);

alter table tracks_genres
add constraint fk_genre
foreign key(genre_id) references genres (id);
--rollback alter table profiles drop constraint fk_track_genre
--rollback alter table profiles drop constraint fk_genre

--changeset liquibase:23
alter table following_followers
drop constraint fk_following_id
foreign key(following_id) references profiles (id);

alter table following_followers
drop constraint fk_follower_id
foreign key(follower_id) references profiles (id);
--rollback alter table profiles drop constraint fk_following_id
--rollback alter table profiles drop constraint fk_follower_id

--changeset liquibase:24
alter table artists_albums
drop constraint fk_artist_id
foreign key(artist_id) references profiles (id);

alter table artists_albums
drop constraint fk_artist_album
foreign key(album_id) references albums (id);
--rollback alter table profiles drop constraint fk_artist_id
--rollback alter table profiles drop constraint fk_artist_album

--changeset liquibase:25
alter table users_playlists
drop constraint fk_user_id
foreign key(user_id) references profiles (id);

alter table users_playlists
drop constraint fk_user_playlists
foreign key(playlist_id) references playlists (id);
--rollback alter table profiles drop constraint fk_user_id
--rollback alter table profiles drop constraint fk_user_playlists
